README.md

feat: updated discalimers

---

core_wrappers.py
qualification_report.py
utils.py
validator.py

Fixes
* Issue with validator , validating apiproxies as sharedflows 

fix: fixed api validator logic

---

.github/workflows/tests.yml
.lycheeignore
README.md

added support to push docker image

added support to push docker image

---

.lycheeignore
README.md

feat: updated readme to add permission details

---

.github/workflows/tests.yml
README.md

feat: updated readme

---

core_wrappers.py
nextgen.py
utils.py
validator.py

Added support for comparing state with target  

---

.github/workflows/tests.yml

feat: publish image only from main

---

.github/workflows/tests.yml
backend.properties
classic.py
core_wrappers.py
nextgen.py
sharding.py
validator.py

added IGNORE_ENV_SHARD flag support and modified pipeline

---

classic.py
nextgen.py

feat: added support to handle empty object names

---

core_wrappers.py

feat: added support for storing target export state

---

README.md
core_wrappers.py
exporter.py
nextgen.py
sample/inputs/opdk.input.properties
sample/inputs/saas.input.properties
sample/inputs/x.input.properties
validator.py

feat: added support for apigee target with DRZ support

---

sharding.py

fix: fixed JSONPATH check

---

core_wrappers.py
qualification_report.py

feat: added failsafe key lookup for visualization

---

utils.py

fix: fixed abrupt proxy unifier exit

---

README.md
core_wrappers.py
main.py
sample/inputs/opdk.input.properties
sample/inputs/saas.input.properties
sample/inputs/x.input.properties

feat: simplified input , removed API_URL, SOURCE_UI_URL

---

backend.properties
core_wrappers.py
main.py
sample/inputs/opdk.input.properties
sample/inputs/saas.input.properties
sample/inputs/x.input.properties
sharding.py
unifier.py

feat: refactored code to move export section to backend.properties

---

backend.properties
core_wrappers.py
sample/inputs/opdk.input.properties
sample/inputs/saas.input.properties
sample/inputs/x.input.properties
topology.py

feat: refactored to moved topology config to backend.properties

---

core_wrappers.py

fix: fixed vizualization issues when target comparison not enabled

---

README.md

docs: update README.md to reflect IGNORE_VIZ usage

---

.github/workflows/tests.yml

feat: modified pull_request to pull_request_target for allowing forked PR

---

README.md
core_wrappers.py
main.py
validator.py

feat: skip-target-validation to skip apigee x validation

---

README.md
core_wrappers.py
main.py
validator.py

Added logic for skipping validation against an Apigee X/Hybrid Organization when someone doesn't want deep validations or if one doesn't have a target Apigee X/Hybrid Organization.

feat: skip validation for target apigee x/hybrid organization import

---

.github/config/commitlint.config.mjs
.github/workflows/static-checks.yml
.github/workflows/tests.yml
sample/inputs/opdk.input.properties

feat: bumped action version

---

Dockerfile

feat: bumped docker base image version

---

classic.py

This PR implements comprehensive diagnostic logging to help troubleshoot API response handling issues, particularly when customers encounter unexpected data types or response structures from Apigee APIs during pagination.
A customer recently encountered an `AttributeError` when the tool expected a list but received a string from an API response during pagination handling. The error occurred at line 99 in `classic.py` during the second API call in the pagination sequence, suggesting the customer had proper permissions (first call succeeded) but encountered an unexpected API response format.
This enhancement adds comprehensive debug-level logging throughout the API response handling pipeline to provide visibility into:
- **API Response Structure**: Log the actual structure and data types of …

feat: Add diagnostic logging for pagination response handling

---

rest.py
tests/test_rest.py

feat: updated condition to log >4xx errors
